# Prevents installation of packages newer than 7 days
# to mitigate supply chain risks
# - https://pnpm.io/settings#minimumreleaseage
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  # - https://github.com/vercel/next.js/security/advisories/GHSA-9qr9-h5gf-34mp
  # - https://github.com/vercel/next.js/security/advisories/GHSA-mwv6-3258-q52c
  # - https://github.com/vercel/next.js/security/advisories/GHSA-w37m-7fhw-fmv9
  # - https://github.com/vercel/next.js/security/advisories/GHSA-5j59-xgg2-r9c4
  - next@16.0.7 || 16.0.9 || 16.0.10
  - '@next/env@16.0.7 || 16.0.9 || 16.0.10'
  - '@next/swc-darwin-arm64@16.0.7 || 16.0.9 || 16.0.10'
  - '@next/swc-linux-x64-gnu@16.0.7 || 16.0.9 || 16.0.10'
  - '@next/swc-linux-x64-musl@16.0.7 || 16.0.9 || 16.0.10'
  - xmldoc@2.0.0
